col_map_macro = {
    "index": "date",
    "BRT-": "brt",
    "CLc1": "clc_1",
    "CLc12": "clc_12",
    "CLc60": "clc_60",
    "WTCLc1": "wtc_1",
    "WTCLc12": "wtc_12",
    "WTCLc60": "wtc_60",
    "LNG-AS": "lng",
    "TR-PETTHP-LNG": "tr_lng",
    "WTI-USG-REF": "wti_ref",
    "DUB-SIN-REF": "dub_ref",
    "CN10YT=RR": "cn_10y",
    "USDSOFR=": "us_intra",
    "US10YT=RR": "us_10y",
    "DE10YT=RR": "de_10y",
    "GB10YT=RR": "gb_10y",
    "JNK": "high_yield_bond",
    ".VIX": "vix",
    "EUR=": "eur_fx",
    "GBP=": "gbp_fx",
    "CNY=": "cny_fx",
}

col_map_meta = {
    "Instrument": "ticker",
    "Date": "date",
    "Exchange Market Identifier Code": "exchange_code",
    "Region of Headquarters": "region_hq",
    "Country of Headquarters": "country_hq",
    "State or Province of Headquarters": "state_province_hq",
    "Organization Founded Year": "founding_year",
    "TRBC Economic Sector Name": "economic_sector",
    "TRBC Business Sector Name": "business_sector",
    "TRBC Industry Group Name": "industry_group",
    "TRBC Industry Name": "industry",
    "TRBC Activity Name": "activity",
}

col_map_fundamentals = {
    "Instrument": "ticker",
    "Date": "date",
    "Period End Date": "period_end_date",
    "Balance Sheet Orig Announce Date": "announce_date",
    "Total Revenue": "revenue",
    "Gross Profit": "gross_profit",
    "EBITDA": "ebitda",
    "EBIT": "ebit",
    "Net Income after Tax": "net_income",
    "Free Cash Flow": "fcf",
    "Total Assets": "total_assets",
    "Total Current Assets": "total_current_assets",
    "Total Liabilities": "total_liabilites",
    "Total Current Liabilities": "total_current_liabilities",
    "Price To Book": "price_book",
    "Long Term Debt Percentage of Total Assets": "long_term_debt_p_assets",
    "Short Term Debt Percentage of Total Assets": "short_term_debt_p_assets",
    "Gross Profitp": "gross_profit_p",
    "EBITDAp": "ebitda_p",
    "EBITp": "ebit_p",
    "Net Income after Taxp": "net_income_p",
}

col_map_stock = {
    "Instrument": "ticker",
    "Date": "date",
    "Company Market Cap": "market_cap",
    "Price Close": "close_price",
    "Currency": "currency",
}

column_mapping = {
    **col_map_macro,
    **col_map_meta,
    **col_map_fundamentals,
    **col_map_stock,
}
