column_mapping = {
    "Instrument": "ticker",
    "Date": "date",
    "Company Market Cap": "market_cap",
    "Price Close": "close_price",
    "Currency": "currency",
    "Period End Date":"period_end_date", 
    "Balance Sheet Orig Announce Date":"announce_date",
    "Total Revenue":"revenue",
    "Gross Profit":"gross_profit",
    "EBITDA": "ebitda", 
    "EBIT":"ebit", 
    "Net Income after Tax":"net_income", 
    "Total Assets":"total_assets",
    "Total Current Assets":"total_current_assets", 
    "Total Liabilities":"total_liabilites",
    "Total Current Liabilities":"total_current_liabilities",
    "Long Term Debt Percentage of Total Assets":"long_term_debt_p_assets",
    "Short Term Debt Percentage of Total Assets":"short_term_debt_p_assets", 
    "Free Cash Flow":"fcf",
    "Gross Profitp":"gross_profit_p",
    "EBITDAp":"ebitda_p",
    "EBITp":"ebit_p",
    "Net Income after Taxp":"net_income_p"
}